apiVersion: v2
name: axelar-node
description: A Helm chart for axelard
type: application
version: 0.1.1
appVersion: 0.1.1
keywords:
  - axelar
  - ledger
  - rpc
home: https://docs.axelar.dev/node/config-node
sources:
  - https://github.com/axelarnetwork
