---
apiVersion: v1
kind: ConfigMap
metadata:
  name: download-snapshot-script
  namespace: {{ .Values.namespace }}
data:
  download-snapshot.sh: |-
{{ $.Files.Get "conf/download-snapshot.sh" | indent 4}}
