---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "app.name" . }}-svc
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '26660'
        prometheus.io/path: '/metrics'
    spec:
      initContainers:
        {{- if .Values.configs.snapshot }}
        - name: download-snapshot
          image: google/cloud-sdk
          command:
          - /usr/local/bin/download-snapshot.sh
          env:
          - name: SNAPSHOT
            value: {{ .Values.configs.snapshot }}
          volumeMounts:
          - mountPath: /mnt/data
            name: data
          - mountPath: /usr/local/bin/
            name: download-snapshot-script
        {{- end }}

      containers:
        - name: {{ include "app.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - startNodeProc
          env:
          - name: HOME_DIR
            value: /home/axelard
          - name: START_REST
            valueFrom:
              configMapKeyRef:
                name: {{ include "app.name" . }}-config
                key: startrest
          - name: PRESTART_SCRIPT
            value: /home/axelard/conf/consume-genesis.sh
          - name: CONFIG_PATH
            value: /home/axelard/conf/
          - name: NODE_MONIKER
            value: {{ .Values.configs.moniker }}
          - name: KEYRING_PASSWORD
            value: {{ .Values.secrets.KEYRING_PASSWORD }}
          - name: AXELARD_CHAIN_ID
            valueFrom:
              configMapKeyRef:
                name: {{ include "app.name" . }}-config
                key: chainid
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if eq (.Values.disableReadinessProbe | default false) false }}
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - catchingupstate=$(wget -q -O- http://127.0.0.1:26657/status | jq '.result.sync_info.catching_up and .result.sync_info.latest_block_height > "0"')
                && if [ $catchingupstate = true ]; then echo "Terminating" && exit 1;
                fi
            failureThreshold: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          {{- end }}
          ports:
          - containerPort: 1317  # rest
          - containerPort: 9090  # grpc
          - containerPort: 26656 # p2p
          - containerPort: 26657 # rpc
          - containerPort: 26660 # prometheus
          volumeMounts:
          - name: configfiles
            mountPath: /home/axelard/conf
          - name: data
            mountPath: /home/axelard/.axelar/data

      volumes:
        - name: configfiles
          configMap:
            name: {{ include "app.name" . }}-configfiles
        - name: download-snapshot-script
          configMap:
            name: download-snapshot-script
            defaultMode: 511
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.volumes.storage }}
      {{- if .Values.volumes.storageClassName }}
      storageClassName: {{ .Values.volumes.storageClassName }}
      {{- end }}
  

