---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ include "app.name" . }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-p2p-net-port
      port: 26656
      protocol: TCP
      targetPort: 26656
    - name: http-tendermint-rpc-port
      port: 26657
      protocol: TCP
      targetPort: 26657
    - name: http-prometheus-port
      port: 26660
      protocol: TCP
      targetPort: 26660
    - name: http-rest-port
      port: 1317
      protocol: TCP
      targetPort: 1317
    - name: grpc-grpc-port
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    {{- include "app.labels" . | nindent 4 }}
